//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Checkin_Checkout_Entities : DbContext
    {
        public Checkin_Checkout_Entities()
            : base("name=Checkin_Checkout_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_BannedUserTable> tb_BannedUserTable { get; set; }
        public virtual DbSet<tb_CSUCheckoutCheckin> tb_CSUCheckoutCheckin { get; set; }
        public virtual DbSet<tb_CSULabInventoryItems> tb_CSULabInventoryItems { get; set; }
        public virtual DbSet<tb_CSULabLocations> tb_CSULabLocations { get; set; }
        public virtual DbSet<tb_CSULabTechs> tb_CSULabTechs { get; set; }
        public virtual DbSet<tb_ItemRepair> tb_ItemRepair { get; set; }
        public virtual DbSet<tb_Reports> tb_Reports { get; set; }
        public virtual DbSet<tb_CSUStudent> tb_CSUStudent { get; set; }
        public virtual DbSet<tb_LongtermWaitlist> tb_LongtermWaitlist { get; set; }
    
        public virtual int DropIndexesScript(Nullable<bool> includeDrop)
        {
            var includeDropParameter = includeDrop.HasValue ?
                new ObjectParameter("IncludeDrop", includeDrop) :
                new ObjectParameter("IncludeDrop", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DropIndexesScript", includeDropParameter);
        }
    
        public virtual int GenerateIndexesScript(Nullable<bool> includeFileGroup, Nullable<bool> includeDrop, Nullable<bool> includeFillFactor)
        {
            var includeFileGroupParameter = includeFileGroup.HasValue ?
                new ObjectParameter("IncludeFileGroup", includeFileGroup) :
                new ObjectParameter("IncludeFileGroup", typeof(bool));
    
            var includeDropParameter = includeDrop.HasValue ?
                new ObjectParameter("IncludeDrop", includeDrop) :
                new ObjectParameter("IncludeDrop", typeof(bool));
    
            var includeFillFactorParameter = includeFillFactor.HasValue ?
                new ObjectParameter("IncludeFillFactor", includeFillFactor) :
                new ObjectParameter("IncludeFillFactor", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateIndexesScript", includeFileGroupParameter, includeDropParameter, includeFillFactorParameter);
        }
    }
}
