//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeraStudents_Entities : DbContext
    {
        public HeraStudents_Entities()
            : base("name=HeraStudents_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_CSUG_DIRECTORY_ALL_LOCAL_No_Dupes_forCheckinCheckout> v_CSUG_DIRECTORY_ALL_LOCAL_No_Dupes_forCheckinCheckout { get; set; }
    }
}
