//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BannedUserTable
    {
        public int Id { get; set; }
        public string CSU_ID { get; set; }
        public Nullable<bool> isBanned { get; set; }
        public Nullable<System.DateTime> DateBanned { get; set; }
        public Nullable<System.DateTime> DateUnbanned { get; set; }
        public string BannedBy { get; set; }
        public string BanReason { get; set; }
        public Nullable<bool> isPermBanned { get; set; }
    }
}
