//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CSUCheckoutCheckin
    {
        public int CheckoutCheckinId { get; set; }
        public string CSU_IDFK { get; set; }
        public int ItemIDFK { get; set; }
        public string CheckoutLabTech { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string CheckinLabTech { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public string CheckoutLocationFK { get; set; }
        public string CheckinLocationFK { get; set; }
        public string ItemUPCFK { get; set; }
        public Nullable<bool> isLate { get; set; }
        public Nullable<bool> isFined { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<bool> isLongterm { get; set; }
        public Nullable<bool> isHome { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> isWaitlistHP { get; set; }
        public Nullable<bool> isWaitlistMac { get; set; }
    }
}
