//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CSULabInventoryItems
    {
        public int ItemId { get; set; }
        public string ItemUPC { get; set; }
        public string ItemDescription { get; set; }
        public string ItemSerialNumber { get; set; }
        public string ItemLocationFK { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> isCheckedOut { get; set; }
        public Nullable<bool> isInRepair { get; set; }
        public Nullable<int> RepairIds { get; set; }
        public Nullable<bool> isWaitlistItem { get; set; }
        public string ReservedTo { get; set; }
    }
}
