//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CSULabLocations
    {
        public string LocationId { get; set; }
        public string LocationNameAcronym { get; set; }
        public string LocactionName { get; set; }
    }
}
