//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CSUStudent
    {
        public int CSUStudentID { get; set; }
        public string CSU_ID { get; set; }
        public string ENAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string PHONE { get; set; }
        public Nullable<bool> SIGNEDWAIVER { get; set; }
    }
}
