//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CSULabTechs
    {
        public int UserID { get; set; }
        public string LocationId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string CSU_ID { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string ENAME { get; set; }
        public bool UserRights { get; set; }
        public Nullable<System.DateTime> DisabledDateTime { get; set; }
        public Nullable<bool> ManagerRights { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> EnabledDateTime { get; set; }
        public string EnabledBy { get; set; }
        public string DisabledBy { get; set; }
    }
}
