//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ItemRepair
    {
        public int RepairId { get; set; }
        public string AssignedTo { get; set; }
        public string Issue { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<System.DateTime> DateRepaired { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<bool> UnRepairable { get; set; }
        public string RepairedBy { get; set; }
        public string ItemUpcFk { get; set; }
        public Nullable<int> ItemIdFk { get; set; }
    }
}
