//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LongtermWaitlist
    {
        public string CSU_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ENAME { get; set; }
        public Nullable<System.DateTime> WAITLISTED { get; set; }
        public string WAITLIST_REASON { get; set; }
        public string WAITLIST_TYPE { get; set; }
        public Nullable<System.DateTime> WAITLIST_NOTIFIED { get; set; }
    }
}
