//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SlingCache
    {
        public string PostId { get; set; }
        public string UserId { get; set; }
        public string PostContent { get; set; }
        public string PostedBy { get; set; }
        public string PostComments { get; set; }
        public Nullable<System.DateTime> Posted { get; set; }
    }
}
