//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TimeClock
    {
        #region Members

        public int TimeClockID { get; set; }
        public string UserIDFK { get; set; }
        public string ClockIn { get; set; }
        public string ClockOut { get; set; }
        public string HoursWorked { get; set; }
        public Nullable<bool> Edited { get; set; }
        public Nullable<bool> Aprroved { get; set; }

        #endregion
    }
}
