//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CheckedOut_active
    {
        #region Members

        public string CSU_IDFK { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public int ItemIDFK { get; set; }
        public string ItemDescription { get; set; }
        public string ItemUPC { get; set; }
        public string ItemSerialNumber { get; set; }
        public int ItemLocationFK { get; set; }
        public string InventoryItemLocation { get; set; }
        public string CheckoutLocationFK { get; set; }
        public string CheckoutLocation { get; set; }

        #endregion
    }
}
