//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Out_App_ULC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CheckinCheckout
    {
        #region Members

        public Nullable<System.DateTime> CheckinDate { get; set; }
        public string CheckinLabTech { get; set; }
        public string CheckinLocationFK { get; set; }
        public int CheckoutCheckinId { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string CheckoutLabTech { get; set; }
        public string CheckoutLocationFK { get; set; }
        public string CSU_IDFK { get; set; }
        public int ItemIDFK { get; set; }
        public Nullable<bool> isBanned { get; set; }

        #endregion
    }
}
